version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - nequi_network

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nequi_api:
    build: .
    container_name: nequi_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    env_file:
      - .env
    environment:
      SPRING_R2DBC_URL: ${URL}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - nequi_network
networks:
  nequi_network:
    driver: bridge
volumes:
  mysql_data:
